# https://travis-ci.org/#!/phlax/debian-build

install:
  - make image

script:
  - echo "Backporting fossil - example from https://wiki.debian.org/SimpleBackportCreation"
  - mkdir build
  - chmod 777 -R build
  - >
    docker run --name bob -v `pwd`/build:/home/bob -ti phlax/debian-build
    bash -c
    "sudo apt-get update -t buster-backports
    && apt source -t testing fossil
    && cd fossil-*/
    && echo 'y' | sudo mk-build-deps -i
    && export DEBFULLNAME=\"Bob the builder\"
    && dch --bpo \"Adding backport!\"
    && dpkg-buildpackage -us -uc"
  - ls build | grep fossil | grep deb

before_deploy:
  - echo $DOCKER_API_TOKEN | docker login -u phlax --password-stdin

deploy:
  provider: script
  script: make hub-image
  skip_cleanup: true
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^(master)$
